version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/lerna-monorepo
hooks:
  ApplicationStart:
    - location: scripts/start_server.sh
      timeout: 60
  ApplicationStop:
    - location: scripts/stop_server.sh
      timeout: 300
  ValidateService:
    - location: scripts/validate_service.sh
