version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/lerna-monorepo
    overwrite: true
file_exists_behavior: OVERWRITE
hooks:
  ApplicationStart:
    - location: packages/scripts/start_server.sh
      timeout: 60
  ApplicationStop:
    - location: packages/scripts/stop_server.sh
      timeout: 300
  ValidateService:
    - location: packages/scripts/validate_service.sh
