version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - echo Installing
  pre_build:
    commands:
      - echo Installing source NPM dependencies.
      - corepack enable pnpm
      - pnpm install --prod
      - cd packages/backend-auth-node/node_modules
      - ls
      - cd @repo
      - ls
artifacts:
  files:
    - "certs/*"
    - "packages/**/*"
    - "appspec.yml"
    - "node_modules/**/*"
    - "package.json"
    - "pnpm-lock.yaml"
    - "scripts/*"
    - "pnpm-workspace.yaml"
    - ".npmrc"
