version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - echo Installing
  pre_build:
    commands:
      - echo Installing source NPM dependencies.
      - corepack enable pnpm
      - pnpm install --prod --filter "backend-auth-node" --filter "backend-fintech-mongo" --filter "backend-fintech-mongo-cron" --filter "kafka-mongo" --filter "grpc-auth-node" --filter "grpc-fintech-node" --filter "graphql-utils" --filter "grpc-utils" --filter "jwt-utils" --filter "kafka-utils" --filter "logs-utils" --filter "mongo-utils" --filter "redis-utils" --filter "utils"
artifacts:
  enable-symlinks: yes
  files:
    - "certs/*"
    - "packages/**/*"
    - "appspec.yml"
    - "node_modules/**/*"
    - "package.json"
    - "pnpm-lock.yaml"
    - "scripts/*"
    - "pnpm-workspace.yaml"
    - ".npmrc"
