version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 12
    commands:
      - echo Installing
  pre_build:
    commands:
      - echo Installing source NPM dependencies.
      - npm install
      - npm run bootstrap
      - cd packages/backend-courses/src
      - ls
      - npm run test
      - cd ..
      - cd ..
      - cd ..
      - ls
  build:
    commands:
      - echo Build started on `date`
      - echo Compiling the Node.js code
      - cd packages/backend-courses/src
      - ls
      - cd ..
      - cd ..
      - cd ..
      - ls
      - npm run build
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - "**/*"
