version: "3"
services:
  backend-courses:
    container_name: backend-courses
    image: node:14
    volumes:
      - nodemodules:/usr/src/service/node_modules
      - .:/usr/src/service
    env_file:
      - ./packages/backend-courses/.env
    working_dir: /usr/src/service/packages/backend-courses
    command: npm run serve
    ports:
      - "4000:4000"
    depends_on:
      - mongo-courses
  reverse-proxy:
    container_name: reverse_proxy
    image: nginx
    depends_on:
      - backend-courses
    volumes:
      - ./reverse_proxy/nginx.conf:/etc/nginx/nginx.conf
      - .:/usr/src/service
    ports:
      - 80:80
volumes:
  nodemodules:
    external: true
