services:
  nginx:
    container_name: nginx
    image: nginx
    volumes:
      - ./packages/nginx:/etc/nginx/conf.d
    ports:
    - '80:80'
    depends_on:
    - backend-auth-rust
    - backend-auth-node

  backend-auth-rust:
    container_name: backend-auth-rust
    image: my-rust-app
    volumes:
      - .:/usr/src/service
    working_dir: /usr/src/service/packages/backend-auth-rust
    ports:
      - "8001:8001"
    depends_on:
      - mongo-fintech
      - redis-auth
    command:
      ["cargo", "run"]

  backend-fintech:
    container_name: backend-fintech
    image: node:18
    volumes:
      - .:/usr/src/service
    working_dir: /usr/src/service/packages/backend-fintech-cassandra
    ports:
      - "4000:4000"
      - "1984:1984"
    depends_on:
      - mongo-fintech
      - backend-auth-node
      - kafka-cassandra
    command:
      ["npm", "run", "start"]

  kafka:
    image: 'bitnami/kafka:latest'
    ports:
      - '9092:9092'
    environment:
      - KAFKA_CFG_NODE_ID=0
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka:9093
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER

  backend-auth-node:
    container_name: backend-auth-node
    image: node:18
    volumes:
      - .:/usr/src/service
    working_dir: /usr/src/service/packages/backend-auth-node
    command: ["./wait-for-it.sh", "kafka-cassandra:9092", "--", "npm", "run", "start"]
    ports:
      - "4002:4002"
      - "1983:1983"
    depends_on:
      - mongo-fintech
      - redis-auth
      - kafka-cassandra

  frontend-fintech:
    container_name: frontend-fintech
    image: node:18
    volumes:
      - .:/usr/src/service
    working_dir: /usr/src/service/packages/frontend-fintech
    command: ["npm", "run", "start"]
    ports:
      - "8000:8000"

  mongo-fintech:
    container_name: mongo-fintech
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"
    logging:
      driver: none
    entrypoint: ["/usr/bin/mongod", "--bind_ip_all"]

  redis-auth:
    container_name: redis-auth
    command: redis-server --appendonly yes
    image: redis
    ports:
      - "6379:6379"
    volumes:
      - ./redis:/data
    logging:
      driver: none

