version: "3"
services:
  backend-courses:
    container_name: backend-courses
    image: node:14
    volumes:
      - nodemodules:/usr/src/service/node_modules
      - .:/usr/src/service
    env_file:
      - ./packages/backend-courses/.env
    working_dir: /usr/src/service
    command: npm run start
    ports:
      - 1234:1234
      - 1235:1235
    links: mongo-courses
  mongo-courses:
    container_name: mongo-courses
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"
volumes:
  nodemodules:
    external: true
