version: "3.4"

x-base: &base
  image: node:14
  volumes:
    - nodemodules:/usr/src/service/node_modules
    - .:/usr/src/service/
  working_dir: /usr/src/service/

services:
  install:
    <<: *base
    command: npm run bootstrap

  build:
    <<: *base
    command: npm run build

volumes:
  nodemodules:
    external: true
