x-base: &base
  image: node:20
  volumes:
    - lerna-node-modules:/usr/src/service/node_modules
    - .:/usr/src/service/
  working_dir: /usr/src/service/

services:
  install:
    <<: *base
    command: bash -c "corepack enable pnpm && pnpm install"
  outdated:
    <<: *base
    command: bash -c "corepack enable pnpm && pnpm outdated"
  update:
    <<: *base
    command: bash -c "corepack enable pnpm && pnpm update"
  proto:
    <<: *base
    command: bash -c "corepack enable pnpm && pnpm proto"
  build:
    <<: *base
    command: bash -c "corepack enable pnpm && pnpm build"

volumes:
  lerna-node-modules:
    external: true
