version: "3"
services:
  kafka-node-fintech:
    container_name: kafka-node-fintech
    image: node:18
    volumes:
      - .:/usr/src/service
    working_dir: /usr/src/service/packages/kafka-node
    ports:
      - "4004:4004"
    depends_on:
      - kafka
      - redis-auth
    command:
      ["npm", "run", "start"]

  kafka:
    container_name: kafka
    image: 'bitnami/kafka:latest'
    ports:
      - '9092:9092'
    environment:
      - KAFKA_CFG_NODE_ID=0
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka:9093
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
  
  cassandra-fintech:
    container_name: cassandra-fintech
    image: cassandra:4.0
    ports:
      - 9042:9042
    volumes:
      - ./cassandra:/var/lib/cassandra
    environment:
      - CASSANDRA_CLUSTER_NAME=cloudinfra
  
  redis-auth:
    container_name: redis-auth
    command: redis-server --appendonly yes
    image: redis
    ports:
      - "6379:6379"
    volumes:
      - ./redis:/data
    logging:
      driver: none
