version: "3"
services:
  relay-gateway:
    container_name: relay-gateway
    image: node:18
    volumes:
      - .:/usr/src/service
    working_dir: /usr/src/service/packages/relay-gateway
    command:
      ["./wait-for-it.sh", "backend-fintech:4000", "--", "npm", "run", "start"]
    ports:
      - "4001:4001"
    depends_on:
      - backend-fintech
      - backend-auth

  backend-fintech:
    container_name: backend-fintech
    image: node:18
    volumes:
      - .:/usr/src/service
    working_dir: /usr/src/service/packages/backend-fintech
    command:
      ["./wait-for-it.sh", "backend-auth:4002", "--", "npm", "run", "start"]
    ports:
      - "4000:4000"
    depends_on:
      - mongo-fintech
      - backend-auth
      - rabbitmq

  backend-auth:
    container_name: backend-auth
    image: node:18
    volumes:
      - .:/usr/src/service
    working_dir: /usr/src/service/packages/backend-auth
    command: ["./wait-for-it.sh", "rabbitmq:5672", "--", "npm", "run", "start"]
    ports:
      - "4002:4002"
      - "1983:1983"
    depends_on:
      - mongo-fintech
      - redis-auth
      - rabbitmq

  frontend-fintech:
    container_name: frontend-fintech
    image: node:18
    volumes:
      - .:/usr/src/service
    working_dir: /usr/src/service/packages/frontend-fintech
    command: ["npm", "run", "start"]
    ports:
      - "8000:8000"

  mongo-fintech:
    container_name: mongo-fintech
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"
    logging:
      driver: none
    entrypoint: ["/usr/bin/mongod", "--bind_ip_all"]

  redis-auth:
    container_name: redis-auth
    command: redis-server --appendonly yes
    image: redis
    ports:
      - "6379:6379"
    volumes:
      - ./redis:/data
    logging:
      driver: none

  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
      - "25672:25672"
    logging:
      driver: none
