x-base: &base
  image: node:22
  volumes:
    - .:/usr/src/service
    - lerna-node-modules:/usr/src/service/node_modules
    - backend-auth-node:/usr/src/service/packages/backend-auth-node/node_modules
    - backend-fintech-mongo:/usr/src/service/packages/backend-fintech-mongo/node_modules
    - backend-fintech-mongo-cron:/usr/src/service/packages/backend-fintech-mongo-cron/node_modules
    - grpc-auth-node:/usr/src/service/packages/grpc-auth-node/node_modules
    - grpc-fintech-node:/usr/src/service/packages/grpc-fintech-node/node_modules
    - kafka-mongo:/usr/src/service/packages/kafka-mongo/node_modules
    - frontend-fintech:/usr/src/service/packages/frontend-fintech/node_modules
    - frontend-fintech-esbuild:/usr/src/service/packages/frontend-fintech-esbuild/node_modules
    - repo-grpc-utils:/usr/src/service/packages/repo-grpc-utils/node_modules
    - repo-graphql-utils:/usr/src/service/packages/repo-graphql-utils/node_modules
    - repo-jwt-utils:/usr/src/service/packages/repo-jwt-utils/node_modules
    - repo-kafka-utils:/usr/src/service/packages/repo-kafka-utils/node_modules
    - repo-logs-utils:/usr/src/service/packages/repo-logs-utils/node_modules
    - repo-mongo-utils:/usr/src/service/packages/repo-mongo-utils/node_modules
    - repo-redis-utils:/usr/src/service/packages/repo-redis-utils/node_modules
    - repo-utils:/usr/src/service/packages/repo-utils/node_modules
  working_dir: /usr/src/service/

services:
  install:
    <<: *base
    command: bash -c "corepack enable pnpm && pnpm install"
  outdated:
    <<: *base
    command: bash -c "corepack enable pnpm && pnpm outdated"
  update:
    <<: *base
    command: bash -c "corepack enable pnpm && pnpm update"
  proto:
    <<: *base
    command: bash -c "corepack enable pnpm && pnpm proto"

volumes:
  lerna-node-modules:
    external: true
  backend-auth-node:
    external: true
  backend-fintech-mongo:
    external: true
  grpc-auth-node:
    external: true
  grpc-fintech-node:
    external: true
  kafka-mongo:
    external: true
  backend-fintech-mongo-cron:
    external: true
  frontend-fintech:
    external: true
  frontend-fintech-esbuild:
    external: true
  repo-grpc-utils:
    external: true
  repo-jwt-utils:
    external: true
  repo-utils:
    external: true
  repo-graphql-utils:
    external: true
  repo-mongo-utils:
    external: true
  repo-redis-utils:
    external: true
  repo-logs-utils:
    external: true
  repo-kafka-utils:
    external: true
