version: "3"
services:
  relay-gateway:
    container_name: relay-gateway
    image: node:18
    volumes:
      - .:/usr/src/service
    working_dir: /usr/src/service/packages/relay-gateway
    command:
      ["./wait-for-it.sh", "backend-courses:4000", "--", "npm", "run", "start"]
    ports:
      - "4001:4001"
    depends_on:
      - backend-courses
      - backend-auth
  backend-courses:
    container_name: backend-courses
    image: node:18
    volumes:
      - .:/usr/src/service
    working_dir: /usr/src/service/packages/backend-courses
    command:
      ["./wait-for-it.sh", "backend-auth:4002", "--", "npm", "run", "start"]
    ports:
      - "4000:4000"
    depends_on:
      - mongo-courses
      - backend-auth
      - rabbitmq
  backend-auth:
    container_name: backend-auth
    image: node:18
    volumes:
      - .:/usr/src/service
    working_dir: /usr/src/service/packages/backend-auth
    command: ["./wait-for-it.sh", "rabbitmq:5672", "--", "npm", "run", "start"]
    ports:
      - "4002:4002"
      - "1983:1983"
    depends_on:
      - mongo-courses
      - redis-auth
      - rabbitmq
  frontend-courses:
    container_name: frontend-courses
    image: node:18
    volumes:
      - .:/usr/src/service
    working_dir: /usr/src/service/packages/frontend-courses
    command: ["npm", "run", "start"]
    ports:
      - "8000:8000"
  mongo-courses:
    container_name: mongo-courses
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"
    logging:
      driver: none
    entrypoint: ["/usr/bin/mongod", "--bind_ip_all", "--replSet", "rs0"]
  redis-auth:
    container_name: redis-auth
    command: redis-server --appendonly yes
    image: redis
    ports:
      - "6379:6379"
    volumes:
      - ./redis:/data
    logging:
      driver: none
  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
      - "25672:25672"
    logging:
      driver: none
