packages:
  - "packages/backend-auth-node"
  - "packages/backend-fintech-mongo"
  - "packages/backend-fintech-mongo-cron"
  - "packages/grpc-auth-node"
  - "packages/grpc-fintech-node"
  - "packages/kafka-mongo"
  - "packages/frontend-fintech"
  - "packages/jest-presets"
  - "packages/typescript-config"
  - "packages/eslint-8-config"
  - "packages/repo-logs-utils"
  - "packages/repo-graphql-utils"
  - "packages/repo-utils"
  - "packages/repo-redis-utils"
  - "packages/repo-mongo-utils"
  - "packages/repo-jwt-utils"
  - "packages/repo-grpc-utils"
