version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/lerna-monorepo
    overwrite: true
hooks:
  ApplicationStart:
    - location: backend-auth-node/scripts/start_server.sh
      timeout: 60
  ApplicationStop:
    - location: backend-auth-node/scripts/stop_server.sh
      timeout: 300
