version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - echo Installing
  pre_build:
    commands:
      - echo Installing source NPM dependencies.
      - corepack enable
      - pnpm install --filter "backend-auth-node"
  build:
    commands:
      - echo Build started on `date`
      - echo Compiling the Node.js code
      - pnpm --filter "backend-auth-node" deploy ./packages/backend-auth-node-deploy
      - cd packages
      - cd backend-auth-node-deploy
      - pnpm build
  post_build:
    commands:
      - echo Build completed on `date`
      - mv ./appspec.yml ../../
      - cd ..
      - sudo rm -r backend-auth-node
      - mv backend-auth-node-deploy backend-auth-node
      - cd backend-auth-node
      - pnpm prune --prod
artifacts:
  files:
    - "certs/*"
    - "packages/backend-auth-node/**/*"
    - "package.json"
    - "appspec.yml"
    - "node_modules/**/*"
