version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - echo Installing
  pre_build:
    commands:
      - echo Installing source NPM dependencies.
      - corepack enable
      - pnpm install --filter "backend-auth-node"
  build:
    commands:
      - echo Build started on `date`
      - mv ./appspec.yml ../../
      - cd ..
      - cd ..
      - pnpm --filter "backend-auth-node" deploy ./packages/backend-auth-node-deploy
      - cd packages/backend-auth-node-deploy
      - pnpm prune --prod
artifacts:
  files:
    - "certs/*"
    - "packages/backend-auth-node-deploy/**/*"
    - "package.json"
    - "appspec.yml"
