[package]
name = "rust-backend-auth"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1.0.2", features = ["macros", "rt-multi-thread"] }
mongodb = "3.1.0"
serde = { version = "1.0.210", features = ["derive"] }
jsonwebtoken = "9.3.0"
redis = "0.27.2"
serde_json = "1.0.128"
tonic = "0.12.3"
prost = "0.13.3"
futures = "0.3.30"

[build-dependencies]
tonic-build = "0.12.3"